/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qcureservations_ver1;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author narag
 */
public class ForgotPassword_ChangePassword extends javax.swing.JFrame {


    /**
     * Creates new form Template
     */
    public ForgotPassword_ChangePassword() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setImageToLabel(logo_img, "src/Image/QCU LOGO 300X300.png");
        String email = EmailSession_ForgotPassword.getUserEmail();
        userEmail.setText(email);
       

    }
    
    private void setImageToLabel(JLabel label, String imagePath) {
    ImageIcon icon = new ImageIcon(imagePath);
    Image img = icon.getImage();
    Image resizedImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
    label.setIcon(new ImageIcon(resizedImg));
}

    private void updatePassword(String newPassword) {
    String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Practice;encrypt=true;trustServerCertificate=true;integratedSecurity=true;";
    
    String updateSQL = "UPDATE [User] SET password = ? WHERE email = ?";
    
    try (Connection conn = DriverManager.getConnection(connectionUrl);
         PreparedStatement pstmt = conn.prepareStatement(updateSQL)) {

        pstmt.setString(1, newPassword);
        pstmt.setString(2, userEmail.getText());

        int rowsAffected = pstmt.executeUpdate();
        if (rowsAffected > 0) {
            System.out.println("Password updated successfully!");
            javax.swing.JOptionPane.showMessageDialog(this, "Password updated successfully!");
        } else {
            System.out.println("No user found with email: " + userEmail);
            javax.swing.JOptionPane.showMessageDialog(this, "No user found with this email.");
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error updating password: " + ex.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panel = new javax.swing.JPanel();
        Menu_Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo_img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Change = new javax.swing.JButton();
        newPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        conPass = new javax.swing.JTextField();
        userEmail = new javax.swing.JLabel();
        Main_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1488, 1196));

        Menu_Panel.setBackground(new java.awt.Color(248, 247, 253));
        Menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Header.setBackground(new java.awt.Color(248, 247, 253));
        Menu_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 58, 93));
        jLabel3.setText("      U ");
        jLabel3.setPreferredSize(new java.awt.Dimension(202, 29));
        Menu_Header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 58, 70));
        jLabel4.setText("          Reservations");
        jLabel4.setPreferredSize(new java.awt.Dimension(202, 29));
        Menu_Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));
        jLabel4.getAccessibleContext().setAccessibleName("          Reserv");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 42, 122));
        jLabel2.setText("QCU Reservations");
        Menu_Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        Menu_Panel.add(Menu_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, 50));

        logo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QCU LOGO 300X300.png"))); // NOI18N
        logo_img.setPreferredSize(new java.awt.Dimension(70, 70));
        Menu_Panel.add(logo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setText("New Password");
        Menu_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        Change.setText("Change");
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        Menu_Panel.add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));
        Menu_Panel.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 190, -1));

        jLabel5.setText("Confirm Password");
        Menu_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        Menu_Panel.add(conPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 190, -1));

        userEmail.setText("email text to hide");
        Menu_Panel.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        Main_Panel.setBackground(Color.WHITE);
        Main_Panel.setPreferredSize(new java.awt.Dimension(1542, 756));

        javax.swing.GroupLayout Main_PanelLayout = new javax.swing.GroupLayout(Main_Panel);
        Main_Panel.setLayout(Main_PanelLayout);
        Main_PanelLayout.setHorizontalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        Main_PanelLayout.setVerticalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Menu_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        // TODO add your handling code here:

        String password = newPass.getText();
        String confirmPassword = conPass.getText();

        if (password.isEmpty() || confirmPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in both fields.");
        } else if (!password.equals(confirmPassword)) {
            javax.swing.JOptionPane.showMessageDialog(null, "Passwords do not match.");
        } else {
            updatePassword(password);
        }
    
    }//GEN-LAST:event_ChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new ForgotPassword_ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Menu_Header;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JTextField conPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logo_img;
    private javax.swing.JTextField newPass;
    private javax.swing.JLabel userEmail;
    // End of variables declaration//GEN-END:variables
}
