/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package PopUp;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.Timer;
import qcureservations_ver2.Dashboard_Main;

/**
 *
 * @author narag
 */
public class LoadingPopUp extends javax.swing.JPanel {

    /**
     * Creates new form Message1
     */
    
   private javax.swing.JFrame loginFrame;

    public LoadingPopUp(javax.swing.JFrame loginFrame) {
        this.loginFrame = loginFrame;
        initComponents();
        startLoading();
    }

    private void startLoading() {
    Timer timer = new Timer(2000, e -> {
        getRootPane().getGlassPane().setVisible(false); // Hide loading popup

        // Open Dashboard_Main
        Dashboard_Main dashboardMain = new Dashboard_Main();
        dashboardMain.setVisible(true);

        // Create greetings popup panel
        Dashboard_Greetings greetingsPopup = new Dashboard_Greetings();

        // Add greetings to Dashboard_Main via GlassPaneOverlay
        GlassPaneOverlay overlay = new GlassPaneOverlay(greetingsPopup);
        dashboardMain.setGlassPane(overlay);
        overlay.setVisible(true);

        // Optionally hide the login frame (if available)
        java.awt.Window loginWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (loginWindow != null) {
            loginWindow.setVisible(false);
        }
    });
    timer.setRepeats(false);
    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Loading = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 247, 253));
        setMaximumSize(new java.awt.Dimension(375, 118));
        setMinimumSize(new java.awt.Dimension(375, 118));
        setPreferredSize(new java.awt.Dimension(375, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        jLabel5.setText("Loading");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("You'll be redirected to the dashboard shortly. ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        Loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loading.gif"))); // NOI18N
        Loading.setLabelFor(Loading);
        add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loading;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
