/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package PopUp;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author narag
 */
public class SuccessSaveChanges_Device extends javax.swing.JPanel {

    /**
     * Creates new form Message1
     */
    
    public SuccessSaveChanges_Device() {
        initComponents();
        // Wait until the component has a size before setting the image
SwingUtilities.invokeLater(() -> {
    setImageToLabel(ImageIcon, "src/Image/SUCCESS ICON.png");
});

    }


    //DO NOT CHANGE THIS - use this for resizing image to match the size of the label
    private void setImageToLabel(JLabel label, String imagePath)
    {
        ImageIcon icon = new ImageIcon(imagePath);
        Image img = icon.getImage();
        Image resizedImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(resizedImg));
    }
public class RoundedButton extends JButton {
    private int cornerRadius;
    private Color borderColor = null; // no border by default

    public RoundedButton(String text, int radius) {
        super(text);
        this.cornerRadius = radius;
        setContentAreaFilled(false);
        setFocusPainted(false);
        setBorderPainted(false);
        setOpaque(false);
    }

    public RoundedButton(String text) {
        this(text, 20);
    }

    public void setBorderColor(Color color) {
        this.borderColor = color;
        repaint();
    }

    public Color getBorderColor() {
        return this.borderColor;
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(getModel().isArmed() ? getBackground().darker() : getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);

        super.paintComponent(g);
        g2.dispose();
    }

    @Override
    protected void paintBorder(Graphics g) {
        if (borderColor != null) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setColor(borderColor);
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, cornerRadius, cornerRadius);
            g2.dispose();
        }
        // else: no border is drawn
    }

    @Override
    public boolean contains(int x, int y) {
        Shape shape = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);
        return shape.contains(x, y);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ImageIcon = new javax.swing.JLabel();
        OkayButton = new RoundedButton("",15);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(436, 159));
        setMinimumSize(new java.awt.Dimension(436, 159));
        setPreferredSize(new java.awt.Dimension(436, 159));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Success!");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Your changes have been successfully saved!");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 30));
        add(ImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 50));

        OkayButton.setBackground(new java.awt.Color(11, 42, 122));
        OkayButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        OkayButton.setForeground(new java.awt.Color(255, 255, 255));
        OkayButton.setText("Okay");
        OkayButton.setBorder(null);
        OkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkayButtonActionPerformed(evt);
            }
        });
        add(OkayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void OkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkayButtonActionPerformed
        // TODO add your handling code here:
         Window topLevelWindow = SwingUtilities.getWindowAncestor(this);
    if (topLevelWindow instanceof JDialog) {
        ((JDialog) topLevelWindow).dispose();  // Close the dialog
    }
    
    // Hide the GlassPaneOverlay
    Window parentWindow = SwingUtilities.getWindowAncestor(this);
    if (parentWindow != null && parentWindow instanceof JFrame) {
        JFrame parentFrame = (JFrame) parentWindow;
        parentFrame.getGlassPane().setVisible(false);  // Hide the glass pane
    }
    }//GEN-LAST:event_OkayButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageIcon;
    private javax.swing.JButton OkayButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
