/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qcureservations_ver2;

import PopUp.Loading;
import qcureservations_ver1.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.*;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.swing.JOptionPane;
import javax.swing.border.*;
import java.awt.*;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import PopUp.GlassPaneOverlay;
import PopUp.Loading;
import PopUp.LoadingPopUp;
/**
 *
 * @author narag
 */
public class ForgotPassword_OTP extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public ForgotPassword_OTP() {
        initComponents();
        
        //DO NOT CHANGE THESE
        setExtendedState(MAXIMIZED_BOTH);
        
        setImageToLabel(logo_img, "src/Image/QCU LOGO 300X300.png");
        
        setImageToLabel(loginImage, "src/Image/SEND EMAIL.png");
        
        HeaderName.setText("<html>"
        + "<span style='color:rgb(11,42,122); font-family:Roboto; font-weight:bold;'>QC</span>"
        + "<span style='color:rgb(239,58,93); font-family:Roboto; font-weight:bold;'>U</span> "
        + "<span style='color:rgb(52,58,70); font-family:Roboto; font-weight:bold;'>Reservations</span>"
        + "</html>");
        
        
        // START NEW CODE HERE

    }
    
    //DO NOT CHANGE THIS
    private void setImageToLabel(JLabel label, String imagePath) {
    ImageIcon icon = new ImageIcon(imagePath);
    Image img = icon.getImage();
    Image resizedImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
    label.setIcon(new ImageIcon(resizedImg));
    }
    
    
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panel = new javax.swing.JPanel();
        loginImage = new javax.swing.JLabel();
        Main_Panel = new javax.swing.JPanel();
        HeaderName = new javax.swing.JLabel();
        logo_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        verify_otp = new RoundedButton("",15);
        forgot_password_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QCU RESERVATIONS | Forgot Password - Verification");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1488, 1196));

        Menu_Panel.setBackground(Color.WHITE);
        Menu_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LOG IN IMAGE.png"))); // NOI18N
        Menu_Panel.add(loginImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 630, 700));

        Main_Panel.setBackground(new java.awt.Color(219, 229, 255));
        Main_Panel.setPreferredSize(new java.awt.Dimension(750, 756));
        Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderName.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        HeaderName.setForeground(new java.awt.Color(11, 42, 122));
        HeaderName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderName.setText("QCU Reservations");
        Main_Panel.add(HeaderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 760, -1));

        logo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QCU LOGO 300X300.png"))); // NOI18N
        logo_img.setPreferredSize(new java.awt.Dimension(100, 100));
        Main_Panel.add(logo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 58, 70));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Organize your time with confidence.");
        Main_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 760, -1));

        userEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        userEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 58, 70), 1, true));
        userEmail.setMargin(new java.awt.Insets(5, 6, 5, 6));
        int arc = 20; // for rounded corners
        int padding = 10;

        userEmail.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(52,58,70), 2, true), // rounded border
            BorderFactory.createEmptyBorder(padding, padding, padding, padding) // padding inside
        ));
        Main_Panel.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 480, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 58, 70));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("OTP Code");
        Main_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 320, -1));

        verify_otp.setBackground(new java.awt.Color(11, 42, 122));
        verify_otp.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        verify_otp.setForeground(new java.awt.Color(255, 255, 255));
        verify_otp.setText("Verify");
        verify_otp.setBorder(null);
        verify_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_otpActionPerformed(evt);
            }
        });
        Main_Panel.add(verify_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 480, 40));

        forgot_password_back.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        forgot_password_back.setForeground(new java.awt.Color(18, 125, 221));
        forgot_password_back.setText("< Forgot Password");
        forgot_password_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_password_backMouseClicked(evt);
            }
        });
        Main_Panel.add(forgot_password_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Menu_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgot_password_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_password_backMouseClicked
        // TODO add your handling code here:
        LogIn login = new LogIn();
        this.setVisible(false);  // Hide the current page
        login.setVisible(true);

    }//GEN-LAST:event_forgot_password_backMouseClicked

    private void verify_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_otpActionPerformed
  
    
                    
    }//GEN-LAST:event_verify_otpActionPerformed
    
    private boolean isPasswordVisible = false; // <-- declare this at the top of your class
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword_OTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderName;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JLabel forgot_password_back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loginImage;
    private javax.swing.JLabel logo_img;
    private javax.swing.JTextField userEmail;
    private javax.swing.JButton verify_otp;
    // End of variables declaration//GEN-END:variables
}
