/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qcureservations_ver2;

import PopUp.Loading;
import qcureservations_ver1.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.*;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.swing.JOptionPane;
import javax.swing.border.*;
import java.awt.*;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import PopUp.GlassPaneOverlay;
import PopUp.Loading;
import PopUp.LoadingPopUp;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;
/**
 *
 * @author narag
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public LogIn() {
        initComponents();
        
        //DO NOT CHANGE THESE
        setExtendedState(MAXIMIZED_BOTH);
        
        setImageToLabel(logo_img, "src/Image/QCU LOGO 300X300.png");
        
        setImageToLabel(loginImage, "src/Image/LOG IN IMAGE.png");
        
        HeaderName.setText("<html>"
        + "<span style='color:rgb(11,42,122); font-family:Roboto; font-weight:bold;'>QC</span>"
        + "<span style='color:rgb(239,58,93); font-family:Roboto; font-weight:bold;'>U</span> "
        + "<span style='color:rgb(52,58,70); font-family:Roboto; font-weight:bold;'>Reservations</span>"
        + "</html>");
        
        setImageToLabel(seeHidePass, "src/Image/see password.png");
        
        
        // START NEW CODE HERE

    }
    
    //DO NOT CHANGE THIS
    private void setImageToLabel(JLabel label, String imagePath) {
    ImageIcon icon = new ImageIcon(imagePath);
    Image img = icon.getImage();
    Image resizedImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
    label.setIcon(new ImageIcon(resizedImg));
    }
    
    
    
   public class RoundedButton extends JButton {
    private int cornerRadius;
    private Color borderColor = null; // no border by default

    public RoundedButton(String text, int radius) {
        super(text);
        this.cornerRadius = radius;
        setContentAreaFilled(false);
        setFocusPainted(false);
        setBorderPainted(false);
        setOpaque(false);
    }

    public RoundedButton(String text) {
        this(text, 20);
    }

    public void setBorderColor(Color color) {
        this.borderColor = color;
        repaint();
    }

    public Color getBorderColor() {
        return this.borderColor;
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(getModel().isArmed() ? getBackground().darker() : getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);

        super.paintComponent(g);
        g2.dispose();
    }

    @Override
    protected void paintBorder(Graphics g) {
        if (borderColor != null) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setColor(borderColor);
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, cornerRadius, cornerRadius);
            g2.dispose();
        }
        // else: no border is drawn
    }

    @Override
    public boolean contains(int x, int y) {
        Shape shape = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);
        return shape.contains(x, y);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panel = new javax.swing.JPanel();
        logo_img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HeaderName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        seeHidePass = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        logIn = new RoundedButton("",15);
        Main_Panel = new javax.swing.JPanel();
        loginImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QCU RESERVATIONS | Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1488, 1196));

        Menu_Panel.setBackground(new java.awt.Color(219, 229, 255));
        Menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QCU LOGO 300X300.png"))); // NOI18N
        logo_img.setPreferredSize(new java.awt.Dimension(100, 100));
        Menu_Panel.add(logo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 125, 221));
        jLabel1.setText("Forgot Password");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Menu_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        HeaderName.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        HeaderName.setForeground(new java.awt.Color(11, 42, 122));
        HeaderName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderName.setText("QCU Reservations");
        Menu_Panel.add(HeaderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 750, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 58, 70));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Password");
        Menu_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 320, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 58, 70));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Organize your time with confidence.");
        Menu_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 690, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 58, 70));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Email");
        Menu_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 320, -1));

        userEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        userEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 58, 70), 1, true));
        userEmail.setMargin(new java.awt.Insets(5, 6, 5, 6));
        int arc = 20; // for rounded corners
        int padding = 10;

        userEmail.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(52,58,70), 2, true), // rounded border
            BorderFactory.createEmptyBorder(padding, padding, padding, padding) // padding inside
        ));
        Menu_Panel.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 480, 40));

        seeHidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/see password.png"))); // NOI18N
        seeHidePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeHidePassMouseClicked(evt);
            }
        });
        Menu_Panel.add(seeHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 475, 30, 30));

        passwordField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passwordField.setPreferredSize(new java.awt.Dimension(3, 19));
        passwordField.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(52,58,70), 2, true), // rounded border
            BorderFactory.createEmptyBorder(padding, padding, padding, padding) // padding inside
        ));
        Menu_Panel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 480, 40));

        logIn.setBackground(new java.awt.Color(11, 42, 122));
        logIn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 255, 255));
        logIn.setText("Log In");
        logIn.setBorder(null);
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        Menu_Panel.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 480, 40));

        Main_Panel.setBackground(Color.WHITE);
        Main_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_Panel.setPreferredSize(new java.awt.Dimension(1542, 756));
        Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LOG IN IMAGE.png"))); // NOI18N
        Main_Panel.add(loginImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 540, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ForgotPassword_GetEmail forgot = new ForgotPassword_GetEmail();
        this.setVisible(false);  // Hide the current page
        forgot.setVisible(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
         // Show loading popup using glass pane
    LoadingPopUp loadingPanel = new LoadingPopUp(this); // pass Login frame
    GlassPaneOverlay glassPaneOverlay = new GlassPaneOverlay(loadingPanel);

    setGlassPane(glassPaneOverlay);
    getGlassPane().setVisible(true);   
    }//GEN-LAST:event_logInActionPerformed
    
    private boolean isPasswordVisible = false; // <-- declare this at the top of your class
    private void seeHidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeHidePassMouseClicked
       if (isPasswordVisible) {
        passwordField.setEchoChar('•'); // mask password
        setImageToLabel(seeHidePass, "src/Image/see password.png");
    } else {
        passwordField.setEchoChar((char) 0); // show password
        setImageToLabel(seeHidePass, "src/Image/hide password.png");
    }
    isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_seeHidePassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderName;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logIn;
    private javax.swing.JLabel loginImage;
    private javax.swing.JLabel logo_img;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel seeHidePass;
    private javax.swing.JTextField userEmail;
    // End of variables declaration//GEN-END:variables
}
